### PR TITLE
Filled in DigiKey part numbers

### LINKED ISSUE #1: Finish BOM for ATmega328P_QFP
The we need to get Digikey part numbers for the [ATmega328p QFP BOM](https://github.com/tribesat/microcontroller_test_designs/blob/master/ATmega328P_QFP/BOM.txt)

To do this look on Digikey for resistors and ceramic capacitors that are the right package size and value. We want the tolerance on the resistors to be around +/-1% and probably +/-5 or 10% on the caps.

### PR DESCRIPTION
**Pull request by eriknstevenson**
Resolves #1

### CODE REVIEW

**Comment by WLaney** [comment]
Looks Great! Can we keep the file as .txt though? I know it's ugly, but it plays nicer with BOM uploaders

**Comment by eriknstevenson** [comment]
Oops! Didn't realize that was a thing. It's back to how it was now.

**Comment by WLaney** [comment]
No worries! It's ready to merge now

**Review by WLaney — APPROVED** [review]

**Comment by eriknstevenson** [comment]
Thanks! I don't have write access to the repository so I will leave that to you (or whoever).

**Comment by kelvinabrokwa** [comment]
@narrative I've added you to the hardware team and given that team write access to this repo. Merge at will!

**Pull request merged**
